### ISSUE TITLE
Est2Phase error

### ISSUE THREAD

**Issue by SimoneAvesani** [suke18/POWSC#1]

**Comment by suke18** [comment]
Just saw the message, your input (Y) of the Est2Phase() function should be a matrix.

**Comment by Yale73** [comment]
Hi @suke18 

Run the same issue. The single-cell experiment is from Seurat and I am sure I have two different conditions, but still get the error.
```
our.sce <- as.SingleCellExperiment(seuratObject)
sce = our.sce[, colData(our.sce)$ID == "2"]
rix = sample(1:nrow(sce), 33917)
sce = sce[rix, ]
est_Paras = Est2Phase(assay(sce))
```

```
Error in colMeans(Y == 0) : 
  'x' must be an array of at least two dimensions
```
I checked the` colMeans(sce)`, but got the following error.
```
Error in base::colMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

```
I checked the `assay(sce[1])`, it is a matrix.
```
1 x 5589 sparse Matrix of class "dgCMatrix"
   [[ suppressing 50 column names ‘T_AAAGATGTCATATCGG-1_1_1’, ‘T_AAAGTAGTCTGCGGCA-1_1_1’, ‘T_AAAGTAGTCTTGTTTG-1_1_1’ ... ]]
                                                                                                          
CERNA1 . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
             
CERNA1 ......

 .....suppressing 5539 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................
```
I checked the two comparisons `unique(sce$dis)`, it is not empty
`[1] "NML" "AD1"`

Can you help me how to set up the matrix to make sure it is not empty?

Thanks,
Yale

**Comment by suke18** [comment]
Hello @Yale73 , thanks for your message. 


> 
> Run the same issue. The single-cell experiment is from Seurat and I am sure I have two different conditions, but still get the error.
> 
> ```
> our.sce <- as.SingleCellExperiment(seuratObject)
> sce = our.sce[, colData(our.sce)$ID == "2"]
> rix = sample(1:nrow(sce), 33917)
> sce = sce[rix, ]
> est_Paras = Est2Phase(assay(sce))
> ```
> 
> ```
> Error in colMeans(Y == 0) : 
>   'x' must be an array of at least two dimensions
> ```
> 
> I checked the` colMeans(sce)`, but got the following error.
> 
> ```
> Error in base::colMeans(x, na.rm = na.rm, dims = dims, ...) : 
>   'x' must be an array of at least two dimensions
> ```
> 
> I checked the `assay(sce[1])`, it is a matrix.
>>  But this is not the **"matrix"** matrix in r. This code snippets might explain the difference and that is the error you got: 
>> ``` 
>>library(POWSC)
>>library(Matrix)
>>m <- Matrix(rpois(1000, lambda = 3), 100,10)
>>Y = as.matrix(m) 
>>Est2Phase(m)
>>Est2Phase(Y)
>> ```

> ```
> 1 x 5589 sparse Matrix of class "dgCMatrix"
>    [[ suppressing 50 column names ‘T_AAAGATGTCATATCGG-1_1_1’, ‘T_AAAGTAGTCTGCGGCA-1_1_1’, ‘T_AAAGTAGTCTTGTTTG-1_1_1’ ... ]]

>> Overall, I think the **"dgCMatrix"** and **"matrix"** are different classes in R. You can try: 
```
Y=assay(sce)[[1]]
cix = which(colData(our.sce)$ID == "2")
Y = Y[, cix]
Y = as.matrix(Y)
est_Paras = Est2Phase(Y)
```
Thanks for the advice. Maybe, I should update my code to accept the dgCMatrix object as well. Please let me know whether it can help.                                                                                          

Best,
Kenong

**Comment by Yale73** [comment]
Hi @suke18,

Thanks for your quick reply. I ran another issue. the dgCMatrix is too large to transfer it into the matrix. It will be great if you can update the package to support dgCMatrix.

```
Y = Y[, cix]
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  index larger than maximal 5589
```

Thanks,
Yale

**Comment by Yale73** [comment]
Hi @suke18,

Thanks for your reply. There is an order issue with your code and I have fixed it.

```
our.sce <- as.SingleCellExperiment(SeuratObject)

Y=our.sce@assays@data@listData[["counts"]]
cix = which(colData(our.sce)$ID == "2")
Y = Y[, cix]
Y = as.matrix(Y)
est_Paras = Est2Phase(Y)
```

But I have another question.

How to set the `sim_size`?
For two-group comparison, the Github main page showed `sim_size = c(100, 400, 1000) # A numeric vector`, while the Vignette in the Github wrote` sim_size = c(100, 200) # A numeric vector.`

How do we set it?

Thanks,
Yale

**Comment by suke18** [comment]
> Thanks for your reply. There is an order issue with your code and I have fixed it.
> > Could you let me know which order issue? 
> ```
> our.sce <- as.SingleCellExperiment(SeuratObject)
> 
> Y=our.sce@assays@data@listData[["counts"]]
> cix = which(colData(our.sce)$ID == "2")
> Y = Y[, cix]
> Y = as.matrix(Y)
> est_Paras = Est2Phase(Y)
> ```
> 
> But I have another question.
> 
> How to set the `sim_size`?
> For two-group comparison, the Github main page showed `sim_size = c(100, 400, 1000) # A numeric vector`, while the Vignette in the Github wrote` sim_size = c(100, 200) # A numeric vector.`
> > You can set up a series of numbers, e.g. sim_size = (200, 500, 1000, 2000), and the software will provide a variety of power evaluations. From the power evaluation curve, you can determine the optimized sample size estimation.

**Comment by Yale73** [comment]
@suke18 
Your code is the following, it seems the same, but the following sce I showed in the above thread has subset the `ID == "2"`. You rerun the subset, which leads to 1 gene in the final Y.
```
Y=assay(sce)[[1]] ### this code doesn't work, I got error `Error in assay(sce)[[1]] : this S4 class is not subsettable`. It should be `assay(sce[1])`, but I used our.sce@assays@data@listData[["counts"]] to get rid of it.
cix = which(colData(our.sce)$ID == "2") ### The sce I used has subset the cells, this step should not run for subset sce. I update the code to use sce directly from the Seurat object and then subset it. That's the order difference.

Y = Y[, cix]
Y = as.matrix(Y)
est_Paras = Est2Phase(Y)
```
Please let me know whether it is clear.

Thanks,
Yale

**Comment by suke18** [comment]
Okay. I don't know your data type. As long as your bug was solved.

**Comment by Yale73** [comment]
@suke18 The issue is that the data matrix extracted from Seurat-derived singleCellExperiment is dgcMatrix, while `Est2Phase` only recognizes matrix. That'why we need `as.matrix()`  to transfer the data matrix before running `Est2Phase()`. Hope it is clear.

Best,
Yale
