### ISSUE TITLE
Error using SC2P for comparison

### ISSUE THREAD

**Issue by Scott1009** [suke18/POWSC#4]
When trying to use SC2P for a two group test, I get the following error:

>pow_rslt = runPOWSC(sim_size=sim_size, est_Paras=est_Paras, per_DE=0.05, DE_Method="SC2P", Cell_Type="PW")

Error in twoPhaseDE0(Y = Y, Z = Z, X = X, Offset = Offset, test.which = test.which,  : 
  The variable to be tested must be a factor
Called from: twoPhaseDE0(Y = Y, Z = Z, X = X, Offset = Offset, test.which = test.which, 
    low.prob = low.prob)

It seems the "cellTypes" column, selected from X into "group", is not a factor.

**Comment by suke18** [comment]
Hello Scott, 

Thanks for testing our package. Thanks for pointing out the error. We have modified the runSC2P function accordingly. 

Best regards,
Kenong
